#All Backend Variables
mysql_user: root
mysql_password: ExpenseApp@1
mysql_host: mysql.gangs.shop

application_url: https://raw.githubusercontent.com/daws-90s/expense-documentation/refs/heads/main/artifacts/expense-backend-v3.tar.gz
directory_name: App directory
file_loaction: /app




